version: '3.8'

services:
  app:
    image: wordpress:fpm-alpine
    depends_on:
      - db
    volumes:
        - wordpress_data:/var/www/html
  db:
    image: mariadb
    environment:
      MARIA_DB_ROOT_PASSWORD: 030720110
      MARIA_DB_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  db_data: